# Generated by Django 4.2 on 2026-02-26 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attribute.attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valor de atributo',
                'verbose_name_plural': 'Valores de atributo',
                'db_table': 'attribute_values',
                'ordering': ['attribute', 'order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
