# Generated by Django 4.2 on 2026-03-08 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import metodos_pagos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('wompi', 'Wompi'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Otro')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.FileField(blank=True, null=True, upload_to=metodos_pagos.models.payment_method_logo_path)),
                ('public_key', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox / Pruebas'), ('production', 'Produccion')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('supported_countries', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pago',
                'db_table': 'payment_methods',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'environment'), name='unique_active_provider_environment'),
        ),
    ]
