# Generated by Django 4.2 on 2026-03-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_active_provider_environment',
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('provider', 'environment')},
        ),
    ]
