# Generated by Django 4.2 on 2026-03-06 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_product_brand_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('offer_text', models.CharField(default='off this week', max_length=100)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('custom_url', models.CharField(blank=True, help_text='URL manual si no hay producto', max_length=500)),
                ('custom_image', models.ImageField(blank=True, help_text='Imagen manual si no hay producto', null=True, upload_to=slider.models.slider_image_path)),
                ('bg_color', models.CharField(default='#0989FF', max_length=7)),
                ('is_light', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Si se selecciona, el boton lleva al producto y puede usar su imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'sliders',
                'ordering': ['order'],
            },
        ),
    ]
