# Generated by Django 4.2 on 2026-03-07 01:16

from django.db import migrations, models
import footer.models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=footer.models.footer_logo_path),
        ),
        migrations.AlterField(
            model_name='footer',
            name='payment_image',
            field=models.FileField(blank=True, null=True, upload_to=footer.models.footer_payment_path),
        ),
    ]
